//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_AiraxpCheckBillPch
    {
        public int id { get; set; }
        public string pchno { get; set; }
        public Nullable<int> wageinout { get; set; }
        public Nullable<int> gid { get; set; }
        public Nullable<int> billstatus { get; set; }
        public Nullable<int> isdel { get; set; }
        public string confirmman { get; set; }
        public Nullable<System.DateTime> confirmdate { get; set; }
        public string confirmremark { get; set; }
        public string addman { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string modifyman { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string delman { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public string remark { get; set; }
        public string ready01 { get; set; }
        public string ready02 { get; set; }
        public string ready03 { get; set; }
        public string ready04 { get; set; }
        public Nullable<int> ready05 { get; set; }
        public Nullable<int> ready06 { get; set; }
        public Nullable<int> ready07 { get; set; }
        public Nullable<decimal> ready08 { get; set; }
        public Nullable<decimal> ready09 { get; set; }
        public Nullable<System.DateTime> ready10 { get; set; }
        public string system { get; set; }
        public Nullable<int> oldid { get; set; }
    }
}
