//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_AiraxpInvoice
    {
        public int id { get; set; }
        public string invoicecode { get; set; }
        public string invoiceDom { get; set; }
        public Nullable<int> sett_gid { get; set; }
        public Nullable<int> payment_gid { get; set; }
        public string payment_code { get; set; }
        public string payment_name { get; set; }
        public string payment_accountno { get; set; }
        public string bank { get; set; }
        public string bankaccount { get; set; }
        public string hbh { get; set; }
        public Nullable<System.DateTime> hbrq { get; set; }
        public string sfg { get; set; }
        public string mdg { get; set; }
        public string xhg { get; set; }
        public Nullable<System.DateTime> arrivedate { get; set; }
        public string description { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> wageall { get; set; }
        public Nullable<decimal> taxrate { get; set; }
        public string remark { get; set; }
        public string invoiceman { get; set; }
        public Nullable<System.DateTime> invoicedate { get; set; }
        public string addman { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string delman { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public string invalidreason { get; set; }
        public string hwnames { get; set; }
        public string servicenames { get; set; }
        public string prices { get; set; }
        public string nums { get; set; }
        public string wagealls { get; set; }
        public string changerates { get; set; }
        public string changerwagealls { get; set; }
        public string wagesources { get; set; }
        public string otheritems { get; set; }
        public string otherinfo { get; set; }
        public Nullable<int> isdel { get; set; }
        public string remarks { get; set; }
        public Nullable<int> isexport { get; set; }
        public string exportman { get; set; }
        public Nullable<System.DateTime> exportdate { get; set; }
        public string ready01 { get; set; }
        public string ready02 { get; set; }
        public string ready03 { get; set; }
        public string ready04 { get; set; }
        public Nullable<int> ready05 { get; set; }
        public Nullable<int> ready06 { get; set; }
        public Nullable<int> ready07 { get; set; }
        public Nullable<System.DateTime> ready08 { get; set; }
        public Nullable<System.DateTime> ready09 { get; set; }
        public Nullable<decimal> ready10 { get; set; }
        public string MAWB { get; set; }
        public string system { get; set; }
        public Nullable<int> oldid { get; set; }
    }
}
