//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_AiraxpAccountWage
    {
        public int id { get; set; }
        public Nullable<int> sid { get; set; }
        public Nullable<int> accountid { get; set; }
        public Nullable<int> wageid { get; set; }
        public Nullable<decimal> wageall { get; set; }
        public Nullable<decimal> finishwageall { get; set; }
        public Nullable<int> billwageid { get; set; }
        public string wagedom { get; set; }
        public string addman { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string remark { get; set; }
        public string ready01 { get; set; }
        public string ready02 { get; set; }
        public string ready03 { get; set; }
        public string ready04 { get; set; }
        public Nullable<int> ready05 { get; set; }
        public Nullable<int> ready06 { get; set; }
        public Nullable<int> ready07 { get; set; }
        public Nullable<System.DateTime> ready08 { get; set; }
        public Nullable<System.DateTime> ready09 { get; set; }
        public Nullable<decimal> ready10 { get; set; }
        public Nullable<int> oldid { get; set; }
    }
}
