//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_AiraxpAccount
    {
        public int id { get; set; }
        public string jobno { get; set; }
        public string accountcode { get; set; }
        public string accountdom { get; set; }
        public Nullable<decimal> taxrate { get; set; }
        public Nullable<int> relid { get; set; }
        public Nullable<int> wageinout { get; set; }
        public Nullable<int> sett_gid { get; set; }
        public Nullable<int> payment_gid { get; set; }
        public string payment_code { get; set; }
        public string payment_name { get; set; }
        public string payment_accountno { get; set; }
        public string payment_lxr { get; set; }
        public string payment_fax { get; set; }
        public Nullable<System.DateTime> payment_deadline { get; set; }
        public string accountman { get; set; }
        public Nullable<System.DateTime> accountdate { get; set; }
        public string hbh { get; set; }
        public Nullable<System.DateTime> hbrq { get; set; }
        public string mawb { get; set; }
        public string hawb { get; set; }
        public string sfg { get; set; }
        public string mdg { get; set; }
        public string zzg { get; set; }
        public string description { get; set; }
        public Nullable<decimal> wageall { get; set; }
        public string currency { get; set; }
        public Nullable<decimal> changerate { get; set; }
        public string packagetype { get; set; }
        public Nullable<int> piece { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> volume { get; set; }
        public Nullable<decimal> jfweight { get; set; }
        public string remark { get; set; }
        public string addman { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string modifyman { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string delman { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public Nullable<int> isdel { get; set; }
        public Nullable<int> isincl { get; set; }
        public Nullable<int> isexport { get; set; }
        public string exportman { get; set; }
        public Nullable<System.DateTime> exportdate { get; set; }
        public string ready01 { get; set; }
        public string ready02 { get; set; }
        public string ready03 { get; set; }
        public string ready04 { get; set; }
        public Nullable<int> ready05 { get; set; }
        public Nullable<int> ready06 { get; set; }
        public Nullable<int> ready07 { get; set; }
        public Nullable<System.DateTime> ready08 { get; set; }
        public Nullable<System.DateTime> ready09 { get; set; }
        public Nullable<decimal> ready10 { get; set; }
        public string system { get; set; }
        public Nullable<int> oldid { get; set; }
        public Nullable<decimal> accountweight { get; set; }
        public Nullable<decimal> zdweight { get; set; }
        public string axpjobno { get; set; }
    }
}
