//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_AiraxpNode
    {
        public int id { get; set; }
        public int sid { get; set; }
        public Nullable<int> codetype { get; set; }
        public string nodename { get; set; }
        public string nodeman { get; set; }
        public System.DateTime codedate { get; set; }
        public string remark { get; set; }
        public string addman { get; set; }
        public System.DateTime adddate { get; set; }
        public string modifyman { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public Nullable<int> timestamp { get; set; }
    }
}
