//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_BqModify
    {
        public int ID { get; set; }
        public string mawb { get; set; }
        public string gzdno { get; set; }
        public string oldmsg { get; set; }
        public string newmsg { get; set; }
        public string newdate { get; set; }
        public string recvdate { get; set; }
        public string recvman { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
    }
}
