//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Dcb_Protect
    {
        public int Id { get; set; }
        public string DcbNo { get; set; }
        public string DcbType { get; set; }
        public Nullable<decimal> DcbWeight { get; set; }
        public Nullable<int> DcbStatus { get; set; }
        public string Dcbkwh { get; set; }
        public Nullable<int> DcbStoreid { get; set; }
        public string DcbTp { get; set; }
        public string DcbRemark { get; set; }
        public string Ckr { get; set; }
        public Nullable<System.DateTime> Ckdate { get; set; }
        public string ready1 { get; set; }
        public Nullable<System.DateTime> ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
    }
}
