//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Dcb_Detaile
    {
        public int ID { get; set; }
        public string GzdNo { get; set; }
        public string DcbNo { get; set; }
        public Nullable<decimal> DcbWeight { get; set; }
        public string Kwh { get; set; }
        public Nullable<int> BreakPiece { get; set; }
        public Nullable<int> MoistPiece { get; set; }
        public Nullable<int> DeformPiece { get; set; }
        public Nullable<int> Piece { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string Bh { get; set; }
        public Nullable<int> Storeid { get; set; }
        public Nullable<int> Zcstatus { get; set; }
        public string Photos { get; set; }
        public string Czman { get; set; }
        public Nullable<System.DateTime> Czdate { get; set; }
        public Nullable<int> Czmethod { get; set; }
        public Nullable<decimal> ready1 { get; set; }
        public Nullable<int> ready2 { get; set; }
        public Nullable<int> ready3 { get; set; }
        public Nullable<System.DateTime> ready4 { get; set; }
        public string ready5 { get; set; }
        public Nullable<int> ready6 { get; set; }
        public string ready7 { get; set; }
        public Nullable<int> ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
        public string ready11 { get; set; }
        public string ready12 { get; set; }
        public string ready13 { get; set; }
        public string ready14 { get; set; }
        public string ready15 { get; set; }
        public string ready16 { get; set; }
        public string ready17 { get; set; }
        public string ready18 { get; set; }
        public string ready19 { get; set; }
        public string ready20 { get; set; }
    }
}
