//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Document_Detaile
    {
        public int ID { get; set; }
        public string JcNo { get; set; }
        public string Mawb { get; set; }
        public Nullable<int> FileType { get; set; }
        public Nullable<int> FileNumber { get; set; }
        public string Remark { get; set; }
        public string Indate { get; set; }
        public string Inman { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
    }
}
