//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_HpoAxpline
    {
        public int id { get; set; }
        public Nullable<int> sid { get; set; }
        public string hpono { get; set; }
        public string dom { get; set; }
        public int gid { get; set; }
        public string hawb { get; set; }
        public Nullable<System.DateTime> dzarriverq { get; set; }
        public string yqsfg { get; set; }
        public string mdg { get; set; }
        public string yqhbh { get; set; }
        public Nullable<System.DateTime> yqhbrq { get; set; }
        public int ybpiece { get; set; }
        public decimal ybweight { get; set; }
        public decimal ybvolume { get; set; }
        public string tradeterm { get; set; }
        public string czremark { get; set; }
        public string otherremark { get; set; }
        public string area { get; set; }
        public string system { get; set; }
        public int status { get; set; }
        public string hwlx { get; set; }
        public string pm { get; set; }
        public string khjcno { get; set; }
        public string bgfs { get; set; }
        public Nullable<System.DateTime> yjjcdate { get; set; }
        public Nullable<System.DateTime> jhjcdate { get; set; }
        public Nullable<decimal> inwageallinprice { get; set; }
        public Nullable<int> isinwageallin { get; set; }
        public Nullable<decimal> self_real_bp_freight_in { get; set; }
        public Nullable<decimal> cus_real_bp_freight_in { get; set; }
        public string address_thr { get; set; }
        public string lxr_thr { get; set; }
        public string phone_thr { get; set; }
        public string address_shr { get; set; }
        public string lxr_shr { get; set; }
        public string phone_shr { get; set; }
        public string mawb_shr { get; set; }
        public string mawb_fhr { get; set; }
        public string hawb_shr { get; set; }
        public string hawb_fhr { get; set; }
        public string addman { get; set; }
        public System.DateTime adddate { get; set; }
        public string modifyman { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string delman { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public int isdel { get; set; }
        public string assignman { get; set; }
        public Nullable<System.DateTime> assigndate { get; set; }
        public Nullable<int> timestamp { get; set; }
    }
}
