//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_HpoAxplineWage
    {
        public int id { get; set; }
        public int sid { get; set; }
        public string items { get; set; }
        public int gid { get; set; }
        public decimal quote { get; set; }
        public int wageinout { get; set; }
        public string wagetype { get; set; }
        public string wagedom { get; set; }
        public decimal changerate { get; set; }
        public decimal num { get; set; }
        public string currency { get; set; }
        public decimal price { get; set; }
        public decimal wageall { get; set; }
        public decimal leastwageall { get; set; }
        public string isfree { get; set; }
        public int confirmstatus { get; set; }
        public string confirmman { get; set; }
        public Nullable<System.DateTime> confirmdate { get; set; }
        public Nullable<int> isdel { get; set; }
        public string addman { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string modifyman { get; set; }
        public Nullable<System.DateTime> modifydate { get; set; }
        public string delman { get; set; }
        public Nullable<System.DateTime> deldate { get; set; }
        public string remark { get; set; }
        public Nullable<int> yssys { get; set; }
        public Nullable<int> isallin { get; set; }
        public Nullable<int> ismodify { get; set; }
        public Nullable<int> timestamp { get; set; }
    }
}
