//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Jjd
    {
        public int ID { get; set; }
        public string GzdNo { get; set; }
        public string Mawb { get; set; }
        public string Hawb { get; set; }
        public string JjTypeCode { get; set; }
        public string JjTypeName { get; set; }
        public Nullable<System.DateTime> JjdateTime { get; set; }
        public Nullable<decimal> BxWeight { get; set; }
        public string BW { get; set; }
        public string BxNo { get; set; }
        public Nullable<int> ZbPiece { get; set; }
        public Nullable<decimal> ZbWeight { get; set; }
        public string Remark { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
    }
}
