//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ex_kw_kwqy
    {
        public int id { get; set; }
        public Nullable<int> storeid { get; set; }
        public string kwqy { get; set; }
        public string bh { get; set; }
        public string hwlx { get; set; }
        public Nullable<int> isauto { get; set; }
        public string kwpackage { get; set; }
        public string kwlx { get; set; }
        public Nullable<int> kwrl { get; set; }
        public Nullable<decimal> kqheight { get; set; }
        public string oper { get; set; }
        public string operdate { get; set; }
        public string remark { get; set; }
        public Nullable<int> usekwrl { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
        public Nullable<int> lockstatus { get; set; }
    }
}
