//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Kw
    {
        public int ID { get; set; }
        public Nullable<int> qyid { get; set; }
        public string Kwh { get; set; }
        public Nullable<int> KwUse { get; set; }
        public Nullable<int> KwStatus { get; set; }
        public Nullable<int> KwNum { get; set; }
        public Nullable<int> UseKwNum { get; set; }
        public string ready1 { get; set; }
        public Nullable<int> ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
    }
}
