//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Log
    {
        public int id { get; set; }
        public string g_title { get; set; }
        public string g_content { get; set; }
        public string czman { get; set; }
        public Nullable<System.DateTime> czdate { get; set; }
        public Nullable<System.DateTime> cdate { get; set; }
        public string remark { get; set; }
        public string ready01 { get; set; }
        public string ready02 { get; set; }
        public string ready03 { get; set; }
        public Nullable<int> ready04 { get; set; }
        public Nullable<int> ready05 { get; set; }
        public Nullable<int> ready06 { get; set; }
        public Nullable<System.DateTime> ready07 { get; set; }
        public Nullable<System.DateTime> ready08 { get; set; }
    }
}
