//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Mawb
    {
        public int ID { get; set; }
        public string mawb { get; set; }
        public string hbh { get; set; }
        public string hbrq { get; set; }
        public string qyg { get; set; }
        public string dest { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
        public string ready11 { get; set; }
        public string ready12 { get; set; }
        public string ready13 { get; set; }
        public string ready14 { get; set; }
        public string ready15 { get; set; }
        public string ready16 { get; set; }
        public string ready17 { get; set; }
        public string ready18 { get; set; }
        public string ready19 { get; set; }
        public string ready20 { get; set; }
    }
}
