//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Photo_Detaile
    {
        public int ID { get; set; }
        public string JcNo { get; set; }
        public string PhotoUrl { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
    }
}
