//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_PoImages
    {
        public int id { get; set; }
        public string jobno { get; set; }
        public string ftpaddress { get; set; }
        public string fileaddress { get; set; }
        public string filename { get; set; }
        public string rel_filename { get; set; }
        public string addman { get; set; }
        public Nullable<System.DateTime> adddate { get; set; }
        public string remark { get; set; }
        public Nullable<int> fileType { get; set; }
        public Nullable<int> timestamp { get; set; }
    }
}
