//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_StoreNewValue
    {
        public int ID { get; set; }
        public string mawbno { get; set; }
        public string jcno { get; set; }
        public Nullable<int> piece { get; set; }
        public Nullable<int> mawbtype { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volum { get; set; }
        public string AddMan { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> Zcstatus { get; set; }
        public Nullable<int> isdel { get; set; }
        public string Remark { get; set; }
        public string Ready01 { get; set; }
        public string Ready02 { get; set; }
        public Nullable<decimal> Ready03 { get; set; }
        public Nullable<decimal> Ready04 { get; set; }
        public Nullable<System.DateTime> Ready05 { get; set; }
    }
}
