//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Store
    {
        public int ID { get; set; }
        public string Gzdno { get; set; }
        public string Mawb { get; set; }
        public string Hawb { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> JcDate { get; set; }
        public Nullable<System.DateTime> JcTime { get; set; }
        public string JcNo { get; set; }
        public string KhJcNo { get; set; }
        public string ShMan { get; set; }
        public string ShDw { get; set; }
        public string WtKhCode { get; set; }
        public string WtKhName { get; set; }
        public string HzdNo { get; set; }
        public string CarNo { get; set; }
        public string Goodstype { get; set; }
        public string DressNorm { get; set; }
        public string Dress { get; set; }
        public Nullable<int> BreakPiece { get; set; }
        public Nullable<int> MoistPiece { get; set; }
        public Nullable<int> DeformPiece { get; set; }
        public string GoodsMark { get; set; }
        public string GoodsRemark { get; set; }
        public Nullable<decimal> GfWeight { get; set; }
        public string FDocument { get; set; }
        public Nullable<int> AllPiece { get; set; }
        public Nullable<int> LPiece { get; set; }
        public Nullable<decimal> AllWeight { get; set; }
        public Nullable<decimal> AllVolum { get; set; }
        public Nullable<int> IsCx { get; set; }
        public Nullable<int> DcbNum { get; set; }
        public Nullable<int> CkType { get; set; }
        public string GoodsTp { get; set; }
        public Nullable<System.DateTime> CkDate { get; set; }
        public string CkMan { get; set; }
        public Nullable<int> Cksd { get; set; }
        public string NCkReason { get; set; }
        public Nullable<System.DateTime> YqCkDate { get; set; }
        public Nullable<int> IsReadyCk { get; set; }
        public string Rkman { get; set; }
        public string Modifyman { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
        public string Photos { get; set; }
        public Nullable<int> Photos_basic { get; set; }
        public Nullable<int> Iskh { get; set; }
        public string Kh_Jcno { get; set; }
        public Nullable<int> Kh_Storeid { get; set; }
        public Nullable<System.DateTime> Kh_Jcdate { get; set; }
        public Nullable<System.DateTime> Kh_Jctime { get; set; }
        public string Kh_Rkman { get; set; }
        public Nullable<int> Kh_AllPiece { get; set; }
        public Nullable<decimal> Kh_AllWeight { get; set; }
        public Nullable<decimal> Kh_AllVolum { get; set; }
        public Nullable<int> Kh_Status { get; set; }
        public string Kh_Remark { get; set; }
        public Nullable<int> IsBackStore { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
        public string ready11 { get; set; }
        public string ready12 { get; set; }
        public string ready13 { get; set; }
        public string ready14 { get; set; }
        public string ready15 { get; set; }
        public string ready16 { get; set; }
        public string ready17 { get; set; }
        public string ready18 { get; set; }
        public string ready19 { get; set; }
        public string ready20 { get; set; }
        public Nullable<int> Isdel { get; set; }
        public Nullable<int> KhHawbid { get; set; }
        public Nullable<int> KhStoreStatus { get; set; }
        public Nullable<int> hwstatus { get; set; }
        public Nullable<int> gid { get; set; }
        public string rkyq { get; set; }
        public string labelman { get; set; }
        public Nullable<System.DateTime> labeldate { get; set; }
        public string accman { get; set; }
        public Nullable<System.DateTime> accdate { get; set; }
        public string securityman { get; set; }
        public Nullable<System.DateTime> securitydate { get; set; }
        public string securitycheckman { get; set; }
        public Nullable<System.DateTime> securitycheckdate { get; set; }
        public string securitybukleman { get; set; }
        public Nullable<System.DateTime> securitybukledate { get; set; }
        public string securityreleaseman { get; set; }
        public Nullable<System.DateTime> securityreleasedate { get; set; }
        public string connman { get; set; }
        public Nullable<System.DateTime> conndate { get; set; }
        public string securityshutoutman { get; set; }
        public Nullable<System.DateTime> securityshutoutdate { get; set; }
        public string timestamp { get; set; }
        public string phman { get; set; }
        public Nullable<System.DateTime> phdate { get; set; }
        public string zcman { get; set; }
        public Nullable<System.DateTime> zcdate { get; set; }
        public Nullable<int> sealpiece { get; set; }
        public Nullable<int> arrowpiece { get; set; }
        public Nullable<int> dangerpiece { get; set; }
        public string otherbreakinfo { get; set; }
        public Nullable<int> sharegoodstype { get; set; }
        public string packagetype { get; set; }
        public string fdocumenttype { get; set; }
        public string productname { get; set; }
        public string drivermobile { get; set; }
        public string KhJcnoHead { get; set; }
        public string KhJcnoEnd { get; set; }
        public Nullable<int> TallyState { get; set; }
        public Nullable<System.DateTime> TallyDate { get; set; }
        public string TallyMan { get; set; }
        public Nullable<int> LabelState { get; set; }
    }
}
