//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_SandK
    {
        public int ID { get; set; }
        public string GzdNo { get; set; }
        public string KhJcxh { get; set; }
        public string OperateMan { get; set; }
        public Nullable<System.DateTime> OperateDate { get; set; }
        public string ConsumMan { get; set; }
        public Nullable<System.DateTime> ConsumDate { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
    }
}
