//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Store_Kh
    {
        public int ID { get; set; }
        public string KhJcxh { get; set; }
        public string YjStore { get; set; }
        public string Mawb { get; set; }
        public string Hawb { get; set; }
        public string Hbh { get; set; }
        public Nullable<System.DateTime> Hbrq { get; set; }
        public Nullable<System.DateTime> Hbsj { get; set; }
        public Nullable<System.DateTime> YjStoreTime { get; set; }
        public Nullable<int> KPiece { get; set; }
        public Nullable<decimal> KWeight { get; set; }
        public Nullable<decimal> KVolum { get; set; }
        public string KhCode { get; set; }
        public string KhName { get; set; }
        public string KhJcbh { get; set; }
        public string GoodsMark { get; set; }
        public string Remark { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
    }
}
