//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Truck
    {
        public int ID { get; set; }
        public string GzdNo { get; set; }
        public string Sfg { get; set; }
        public string Sfd { get; set; }
        public string Servicetype { get; set; }
        public string Dest { get; set; }
        public Nullable<int> Truckid { get; set; }
        public string TruckNo { get; set; }
        public string TruckName { get; set; }
        public string TruckPhone { get; set; }
        public string TruckStype { get; set; }
        public Nullable<System.DateTime> TruckTime { get; set; }
        public string truckaddman { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<decimal> hgprice { get; set; }
        public Nullable<decimal> hgweight { get; set; }
        public string FengNo { get; set; }
        public string CusCarNo { get; set; }
        public Nullable<int> islockstatus { get; set; }
        public string islockaddman { get; set; }
        public Nullable<System.DateTime> islockaddtime { get; set; }
        public string AddMan { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> isdel { get; set; }
        public string DelMan { get; set; }
        public Nullable<System.DateTime> DelDate { get; set; }
        public Nullable<int> isedit { get; set; }
        public Nullable<int> ishgedit { get; set; }
        public Nullable<int> wooddcbnum { get; set; }
        public Nullable<int> othernum { get; set; }
        public string Remark { get; set; }
        public string Ready01 { get; set; }
        public string Ready02 { get; set; }
        public Nullable<decimal> Ready03 { get; set; }
        public Nullable<decimal> Ready04 { get; set; }
        public Nullable<System.DateTime> Ready05 { get; set; }
        public string Receiptno { get; set; }
        public Nullable<int> TranStatus { get; set; }
        public Nullable<System.DateTime> TruckBackTime { get; set; }
        public Nullable<int> BreakPiece { get; set; }
        public Nullable<int> MoistPiece { get; set; }
        public Nullable<int> DeformPiece { get; set; }
        public Nullable<int> TruckGrade { get; set; }
        public Nullable<decimal> Truckfee1 { get; set; }
        public Nullable<decimal> Truckfee2 { get; set; }
        public string TruckJobno { get; set; }
        public Nullable<int> Ischeck1 { get; set; }
        public Nullable<int> Ischeck2 { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> TGroup { get; set; }
        public string Truckfeeremark { get; set; }
        public string jcno { get; set; }
        public Nullable<int> dcbid { get; set; }
    }
}
