//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Truck_Protect
    {
        public int id { get; set; }
        public Nullable<int> Tid { get; set; }
        public string jcNo { get; set; }
        public string DCBNO { get; set; }
        public string AddMan { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Remark { get; set; }
        public string Ready01 { get; set; }
        public string Ready02 { get; set; }
        public Nullable<decimal> Ready03 { get; set; }
        public Nullable<decimal> Ready04 { get; set; }
        public Nullable<System.DateTime> Ready05 { get; set; }
    }
}
