//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_Volume_Detaile
    {
        public int ID { get; set; }
        public string GzdNo { get; set; }
        public Nullable<decimal> Longs { get; set; }
        public Nullable<decimal> Widths { get; set; }
        public Nullable<decimal> Heights { get; set; }
        public Nullable<int> Piece { get; set; }
        public string PackageTypeCode { get; set; }
        public string PackageTypeName { get; set; }
        public string IsLimit { get; set; }
        public string ready1 { get; set; }
        public string ready2 { get; set; }
        public string ready3 { get; set; }
        public string ready4 { get; set; }
        public string ready5 { get; set; }
        public string ready6 { get; set; }
        public string ready7 { get; set; }
        public string ready8 { get; set; }
        public string ready9 { get; set; }
        public string ready10 { get; set; }
    }
}
