//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ex_WffAxpline
    {
        public int id { get; set; }
        public int wffid { get; set; }
        public string area { get; set; }
        public string system { get; set; }
        public string jobno { get; set; }
        public string czlx { get; set; }
        public int gid { get; set; }
        public string hwxz { get; set; }
        public string khjcbh { get; set; }
        public string mawb { get; set; }
        public Nullable<int> realpiece { get; set; }
        public Nullable<decimal> realweight { get; set; }
        public Nullable<decimal> realvolume { get; set; }
        public Nullable<int> zdpiece { get; set; }
        public Nullable<decimal> zdweight { get; set; }
        public Nullable<decimal> zdvolume { get; set; }
        public Nullable<decimal> accountweightin { get; set; }
        public Nullable<decimal> accountweightout { get; set; }
        public Nullable<decimal> jfweightin { get; set; }
        public string sfg { get; set; }
        public string zzg { get; set; }
        public string hbh { get; set; }
        public Nullable<System.DateTime> hbrq { get; set; }
        public Nullable<System.DateTime> qfsj { get; set; }
        public string bgxx { get; set; }
        public string bglx { get; set; }
        public int dzstatus { get; set; }
        public int pcstatus { get; set; }
        public int bgstatus { get; set; }
        public string remark { get; set; }
        public string addman { get; set; }
        public System.DateTime adddate { get; set; }
        public string modifyman { get; set; }
        public System.DateTime modifydate { get; set; }
        public string delman { get; set; }
        public System.DateTime deldate { get; set; }
        public Nullable<int> isdel { get; set; }
        public string delreason { get; set; }
    }
}
