//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IM_Gzd
    {
        public int ID { get; set; }
        public string GzdNo { get; set; }
        public string mawb { get; set; }
        public string hawb { get; set; }
        public string TCID { get; set; }
        public string PPCC { get; set; }
        public bool YJmark { get; set; }
        public string EndDate { get; set; }
        public string oper { get; set; }
        public string Area { get; set; }
        public int Piece { get; set; }
        public decimal Weight { get; set; }
        public bool IsEnd { get; set; }
        public string Ready1 { get; set; }
        public string Ready2 { get; set; }
        public string Ready3 { get; set; }
        public string Ready4 { get; set; }
        public string Ready5 { get; set; }
        public int Ready6 { get; set; }
        public int Ready7 { get; set; }
        public int Ready8 { get; set; }
        public int Ready9 { get; set; }
        public string Ready10 { get; set; }
        public string InvoiceTime { get; set; }
    }
}
