//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WcPoManagementNew_2011Entities1 : DbContext
    {
        public WcPoManagementNew_2011Entities1()
            : base("name=WcPoManagementNew_2011Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ex_AiraxpAccount> Ex_AiraxpAccount { get; set; }
        public DbSet<Ex_AiraxpAccountWage> Ex_AiraxpAccountWage { get; set; }
        public DbSet<Ex_AiraxpCheckBillPch> Ex_AiraxpCheckBillPch { get; set; }
        public DbSet<Ex_AiraxpCheckBillPchWage> Ex_AiraxpCheckBillPchWage { get; set; }
        public DbSet<Ex_AiraxpInvoice> Ex_AiraxpInvoice { get; set; }
        public DbSet<Ex_AiraxpInvoiceWage> Ex_AiraxpInvoiceWage { get; set; }
        public DbSet<Ex_AiraxpNode> Ex_AiraxpNode { get; set; }
        public DbSet<Ex_Axpline> Ex_Axpline { get; set; }
        public DbSet<Ex_AxplineWage> Ex_AxplineWage { get; set; }
        public DbSet<Ex_HpoAxpline> Ex_HpoAxpline { get; set; }
        public DbSet<Ex_HpoAxplineWage> Ex_HpoAxplineWage { get; set; }
        public DbSet<Ex_PoImages> Ex_PoImages { get; set; }
        public DbSet<Ex_Store> Ex_Store { get; set; }
        public DbSet<Ex_Volume_Detaile> Ex_Volume_Detaile { get; set; }
        public DbSet<Ex_WffAaxplineWage> Ex_WffAaxplineWage { get; set; }
        public DbSet<Ex_WffAxpline> Ex_WffAxpline { get; set; }
    }
}
