//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WcStore_2011Entities : DbContext
    {
        public WcStore_2011Entities()
            : base("name=WcStore_2011Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ex_BqModify> Ex_BqModify { get; set; }
        public DbSet<Ex_Dcb_Detaile> Ex_Dcb_Detaile { get; set; }
        public DbSet<Ex_Dcb_Protect> Ex_Dcb_Protect { get; set; }
        public DbSet<Ex_Document_Detaile> Ex_Document_Detaile { get; set; }
        public DbSet<Ex_ExpDataLog> Ex_ExpDataLog { get; set; }
        public DbSet<Ex_Hawb> Ex_Hawb { get; set; }
        public DbSet<Ex_HbqScan> Ex_HbqScan { get; set; }
        public DbSet<Ex_Jjd> Ex_Jjd { get; set; }
        public DbSet<Ex_Kw> Ex_Kw { get; set; }
        public DbSet<ex_kw_kwqy> ex_kw_kwqy { get; set; }
        public DbSet<Ex_Log> Ex_Log { get; set; }
        public DbSet<Ex_Mawb> Ex_Mawb { get; set; }
        public DbSet<Ex_Photo_Detaile> Ex_Photo_Detaile { get; set; }
        public DbSet<Ex_SandK> Ex_SandK { get; set; }
        public DbSet<Ex_Store> Ex_Store { get; set; }
        public DbSet<Ex_Store_Expand> Ex_Store_Expand { get; set; }
        public DbSet<Ex_Store_Kh> Ex_Store_Kh { get; set; }
        public DbSet<Ex_StoreManager> Ex_StoreManager { get; set; }
        public DbSet<Ex_StoreNewValue> Ex_StoreNewValue { get; set; }
        public DbSet<Ex_Truck> Ex_Truck { get; set; }
        public DbSet<Ex_Truck_Detaile> Ex_Truck_Detaile { get; set; }
        public DbSet<Ex_Truck_Protect> Ex_Truck_Protect { get; set; }
        public DbSet<Ex_Volume_Detaile> Ex_Volume_Detaile { get; set; }
        public DbSet<IM_Gzd> IM_Gzd { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Tmp__Ex_Dcb_Protect> Tmp__Ex_Dcb_Protect { get; set; }
    }
}
