//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp__Ex_Dcb_Protect
    {
        public int id { get; set; }
        public string dcbno { get; set; }
        public Nullable<decimal> dcbweight { get; set; }
        public Nullable<int> status { get; set; }
    }
}
